FROM httpd:2.4

COPY xploitcraft.conf /usr/local/apache2/conf/extra/

COPY httpd.conf /usr/local/apache2/conf/httpd.conf

RUN mkdir -p /usr/local/apache2/logs && chmod -R 777 /usr/local/apache2/logs

EXPOSE 8080

CMD ["httpd-foreground"]

