FROM node:23-alpine
RUN apk add --no-cache bash curl
RUN npm install -g npm@10.9.2
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
RUN npm install -g serve
RUN chown -R node:node /app
USER node
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]


